url: "https://wtburadio.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "WTBU Radio" # the name of your site, e.g. ACME Corp.

permalink: pretty

collections:
  pages:
    output: true