#url: "https://wtburadio.org" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://wtbu-radio.firebaseapp.com"
baseurl: "" # the subpath of your site, e.g. /blog
title: "WTBU Radio" # the name of your site, e.g. ACME Corp.

permalink: pretty

collections:
  pages:
    output: true
    permalink: pretty
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

plugins: [jekyll-paginate-v2]

exclude: ['post-converter']

# Site configuration for the Jekyll 3 Pagination Gem
pagination:
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  sort_reverse: true

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.